version: "3.8"

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    ports:
      - 5000:5000

  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    ports:
      - 8080:8080

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'

  database:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database
    ports:
      - '5432:5432'

  proxy:
    image: nginx
    volumes:
      # - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./proxy.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80