version: "3.8"

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    ports:
      - 5000:5000

  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    ports:
      - 8080:8080
