FROM node:16-alpine

WORKDIR /app

COPY ./example-frontend .

EXPOSE 5000


ENV REACT_APP_BACKEND_URL="http://127.0.0.1/api"

RUN npm i --silent --production && npm run build && npm i -g serve && \
    find /app -mindepth 1 -not -regex '^/app/build.*' -delete
    
CMD ["serve", "-s", "-l", "5000", "build"]